run "curl -s https://getcomposer.org/installer | php -d allow_url_fopen=on"
run "cp #{release_path}/app/config/parameters.yml.example #{release_path}/app/config/parameters.yml"
run "ln -s #{release_path}/web/app.php #{release_path}/web/index.php"
run "php -d allow_url_fopen=on composer.phar install"
run "sed  -e 's/root \/data\/symfony_app\/current/\/data\/symfony_app\/current/web' > /etc/nginx/servers/symfony_app.conf > /etc/nginx/servers/symfony_app.conf.tmp; cp /etc/nginx/servers/symfony_app.conf.tmp /etc/nginx/servers/symfony_app.conf''"